- name: install docker
  become: true
  ansible.builtin.apt:
    update_cache: yes
    name:
    - docker-ce
    - docker-ce-cli
    - docker-ce-rootless-extras
    - docker-compose
    state: present
  notify: restart docker

- name: start and enable docker
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes

# - name: python docker (for checkmk)
#   become: true
#   ansible.builtin.apt:
#     update_cache: yes
#     name: python3-docker
#     state: present
